import '../styles/globals.css';
import {AppProps} from "next/app";
import Head from "next/head";

function MyApp({Component, pageProps}: AppProps): JSX.Element {
  return <>
    <Head>
      <title>My Top App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Component {...pageProps} />
  </>;
}

export default MyApp;
